messages:

  # 접두사
  prefix: "&c[경고] &r"

  # 콘솔에서 명령어 사용 시 출력되는 메세지
  only_player: "&c콘솔에서 사용할 수 없는 명령어입니다."

  # 경고
  warn:

    # 도움말 명령어 사용 시 출력되는 메세지
    help:
      - "/경고 확인 <플레이어> : 경고를 확인합니다."
      - "/경고 지급 <플레이어> <횟수> <사유>: 경고를 지급합니다."
      - "/경고 차감 <플레이어> <횟수> <사유>: 경고를 차감합니다."
      - "/경고 설정 <플레이어> <횟수> <사유>: 경고를 설정합니다."
      - "/경고 액션 <횟수> <액션> : 경고 횟수에 따른 액션을 설정합니다."

    # 경고 확인 명령어 사용 시 출력 되는 메세지
    check: "{player} 님의 경고 횟수는 {amount}회 입니다."

    # 경고 지급 명령어 사용 시 출력 되는 메세지
    give: 
      - "관리자가 {player} 에게 경고 {amount} 을/를 추가했습니다."
      - "사유 : {reason}"

    # 경고 차감 명령어 사용 시 출력 되는 메세지
    take:
      - "관리자가 {player} 의 경고 {amount} 을/를 차감했습니다."
      - "사유 : {reason}"

    # 경고 설정 명령어 사용 시 출력되는 메세지
    set:
      - "관리자가 {player} 의 경고를 {amount} (으)로 설정했습니다."
      - "사유 : {reason}"

    # 경고 액션 명령어 사용 시 출력되는 메세지
    setAction: "경고 {line} 회의 액션을 {action} (으)로 설정했습니다."

errorMessages:

  # 펄미션이 없을 시 출력 되는 메세지
  noPermission: "&c당신은 해당 명령어를 사용할 권한이 없습니다."

  warn:

    # 플레이어를 입력하지 않았을 시 출력되는 메세지
    noPlayer: "&c경고를 확인할 플레이어를 입력해주세요."

    # 플레이어를 찾지 못할 시 출력되는 메세지
    notFoundPlayer: "&c플레이어를 찾을 수 없습니다."

    # 횟수를 입력하지 않았을 시 출력되는 메세지
    noAmount: "&c횟수를 입력해주세요."

    # 경고 횟수를 입력하지 않았을 시 출력되는 메세지
    noActionLine: "&c액션을 실행할 경고 횟수를 입력해주세요."

    # 액션을 입력하지 않았을 시 출력되는 메세지
    noAction: "&c액션을 입력해주세요."

    # 횟수를 잘못 입력했을 시 출력되는 메세지
    invalidAmount: "&c올바르지 않은 형식입니다."

    # 액션을 잘못 입력했을 시 출력되는 메세지
    invalidAction: "&c올바르지 않은 액션입니다."
  

others:

  # 경고 메시지 공개 여부 (전체메시지/개인메세지)
  public: true

  # 경고 횟수에 따른 액션
  actions:
    1: MESSAGE
    2: MESSAGE
    3: MESSAGE
    4: KICK
    5: BAN

  actions_value:
      message: "&c당신은 관리자로부터 경고를 받았습니다. 주의하세요."
      kick: "&c당신은 경고 누적으로 인해 서버에서 추방되었습니다. 주의하세요."
      ban: "&c당신은 경고 누적으로 인해 서버에서 차단되었습니다."  
      ban-ip: "&c당신은 경고 누적으로 인해 서버에서 차단되었습니다."
  