name: ST-Warn
main: net.starly.warn.WarnMain
author: Starly Team
website: http://starly.kr/discord

description: Warn Plugin.

softdepend:
  - ST-Core

version: 1.0_Alpha
api-version: 1.13

commands:
  warning:
    description: 경고 명령어
    aliases: [ "warn", "경고", "처벌" ]