name: ST-Warn
main: net.starly.warn.WarnMain
author: Starly Team
website: http://starly.kr/

description: Warning Plugin.

softdepend:
  - ST-Core

version: 1.0.1
api-version: 1.13

commands:
  warning:
    description: 경고 명령어
    aliases: [ warn, 경고 ]