name: ST-Warn
main: net.starly.warn.WarnMain
author: Starly Team
website: http://starly.kr/discord

description: Warn Plugin.

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

commands:
  warn:
    aliases: ["경고"]